### ISSUE TITLE
Manage Markdown

### ISSUE THREAD

**Issue by Thibault5** [lenra-io/docs#1]
In order to have more complete documentation we should manage adding Markdown content to the documentation pages.
https://github.com/showdownjs/showdown
For example, when generating the /components/button.schema.html in english language we try to get the file src/markdown/components/button.schema-en.md. If it exists we transform the Markdown to HTML with [showdown](https://github.com/showdownjs/showdown) and add the resulting HTML to the page, under or in replacement of the description.

**Comment by taorepoara** [comment]
Done
