### ISSUE TITLE
[Task] Add an offline search feature 

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/docs#115]
## What should be done 
Add the offline search feature.
- We want to add a search bar in every page of the doc (header) to search in it.
- The search should work offline if possible.
- Try to mimic the Elixir example for the list under the input + the search page result.
- The page show a line or two of the full text where the result is found AND the link of this page + anchor (see elixir page example)

## Technical recommandation
A lib that should be capable of such feature : https://lunrjs.com/
An example of a search that actually uses this lib : https://hexdocs.pm/elixir

## Ecological concerns
The offline feature is important to limit the data usage in general.

**Comment by Nesqwik** [comment]
Maybe, but first we should implement a simple offline version

**Comment by taorepoara** [comment]
> Maybe, but first we should implement a simple offline version

The search engine is working and (must be tested) I think it works offline.

**Comment by Nesqwik** [comment]
It's not released yet ? 
Also, there is no staging docs ?

If it's done, we can close this issue
