### ISSUE TITLE
[Task] BorderRadius@radiusType in BorderRadius link to home page

### ISSUE THREAD

**Issue by shiipou** [lenra-io/docs#59]
## What should be done 
The [BorderRadius@radiusType](https://docs.staging.lenra.io/components-api/defs/borderRadius.html#radiusType) try to open new page instead of linking to anchor.

I think the `@` must be change to `#`

**Comment by taorepoara** [comment]
This have change in the new doc, but there is another problem. The radiusType title id starts with a `#` that have to be removed.
